name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # Metrics Language Plugin
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage  # Additionally display total bytes size and percentage
          # Metrics Isometric Commit Calendar Plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year  # Display full year instead of half year
